# Generated by Django 3.2.5 on 2021-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=63, unique=True)),
                ('a', models.CharField(max_length=63, unique=True)),
                ('b', models.CharField(max_length=63, unique=True)),
                ('c', models.CharField(max_length=63, unique=True)),
                ('d', models.CharField(max_length=63, unique=True)),
                ('e', models.CharField(max_length=63, unique=True)),
                ('f', models.CharField(max_length=63, unique=True)),
                ('g', models.CharField(max_length=63, unique=True)),
                ('h', models.CharField(max_length=63, unique=True)),
                ('i', models.CharField(max_length=63, unique=True)),
                ('j', models.CharField(max_length=63, unique=True)),
                ('k', models.CharField(max_length=63, unique=True)),
                ('l', models.CharField(max_length=63, unique=True)),
                ('m', models.CharField(max_length=63, unique=True)),
                ('n', models.CharField(max_length=63, unique=True)),
                ('o', models.CharField(max_length=63, unique=True)),
                ('p', models.CharField(max_length=63, unique=True)),
                ('q', models.CharField(max_length=63, unique=True)),
                ('r', models.CharField(max_length=63, unique=True)),
                ('s', models.CharField(max_length=63, unique=True)),
                ('t', models.CharField(max_length=63, unique=True)),
                ('u', models.CharField(max_length=63, unique=True)),
                ('v', models.CharField(max_length=63, unique=True)),
                ('w', models.CharField(max_length=63, unique=True)),
                ('x', models.CharField(max_length=63, unique=True)),
                ('y', models.CharField(max_length=63, unique=True)),
                ('z', models.CharField(max_length=63, unique=True)),
            ],
        ),
    ]
