# Generated by Django 3.2.5 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_atlas_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='J',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Z',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Atlas',
        ),
    ]
