from django.contrib import admin
from .models import A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z#Room,


# Register your models hoere.
#admin.site.register(Room)
admin.site.register(A)
admin.site.register(B)
admin.site.register(C)
admin.site.register(D)
admin.site.register(E)
admin.site.register(F)
admin.site.register(G)
admin.site.register(H)
admin.site.register(I)
admin.site.register(J)
admin.site.register(K)
admin.site.register(L)
admin.site.register(M)
admin.site.register(N)
admin.site.register(O)
admin.site.register(P)
admin.site.register(Q)
admin.site.register(R)
admin.site.register(S)
admin.site.register(T)
admin.site.register(U)
admin.site.register(V)
admin.site.register(W)
admin.site.register(X)
admin.site.register(Y)
admin.site.register(Z)
